# This workflow will build and run the test project ./test/ResultTests.fsproj

name: Build and Test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore tools (paket)
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet paket restore
    - name: Build
      run: dotnet build ./test/ResultTests.fsproj
    - name: Test
      run: dotnet run --project ./test/ResultTests.fsproj --no-build --verbosity normal
